services:
  operation-service:
    build: .
    container_name: "operation-service"
    image: "mini-bank-operation-service"

    ports:
      - 8085:8085

    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - INTEGRATION_ACCOUNT_SERVICE_URL=${INTEGRATION_ACCOUNT_SERVICE_URL}

    depends_on:
      db-service:
        condition: service_started
        required: true
