server:
  post: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/users
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: "${app.schema}"
    show-sql: true
    properties:
      hibernate:
        default_schema: "${app.schema}"

  liquibase:
    changelog: "classpath:db/changelog.yml"
    defaultSchema: "${app.schema}"

springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true
  api-docs:
    resolve-schema-properties: true

jwt:
  key:
    public: "classpath:keys/public.key"
    private: "classpath:keys/private.key"

app:
  schema: "user_service"
  token-duration: 180
  account:
    type: "45678"
    host: "localhost"
    port: "8190"
    url: http://${app.account.host}:${app.account.port}

#debug: true
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: TRACE
