server:
  post: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/users
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: "user_service"
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    changelog: "classpath:db/changelog.yml"
    defaultSchema: "user_service"

springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true

jwt:
  key:
    public: "classpath:keys/public.key"
    private: "classpath:keys/private.key"

app:
  account:
    host: localhost
    port: 8190
    url: http://${app.account.host}:${app.account.port}/profile

#debug: true
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: TRACE
#    org.springframework.security: TRACE
