server:
  port: 8190
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fakedb
    username: fakeuser
    password: fakepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        default_schema: "${app.schema}"
    hibernate:
      ddl-auto: validate
      default_schema: "${app.schema}"
  liquibase:
    defaultSchema: "${app.schema}"
springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true

app:
  schema: "account_service"
