services:
  user-service:
    build: .
    container_name: "user-service"
    image: "mini-bank-user-service"
    restart: always

    ports:
      - 32081:8080

    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APP_ACCOUNT_HOST=${USER_SERVICE_ACCOUNT_HOST}
      - APP_ACCOUNT_PORT=${USER_SERVICE_ACCOUNT_PORT}
      - APP_ACCOUNT_TYPE=${USER_SERVICE_DEFAULT_ACCOUNT_TYPE}

    depends_on:
      db-service:
        condition: service_started
        required: true
