services:
  user-service:
    build: .
    container_name: "user-service"

    ports:
      - 32081:8080

    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

    depends_on:
      db-service:
        condition: service_started
        required: true
